/* 
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

-- src/lib.rs:33
-- pgmer2::mr_service_url
CREATE  FUNCTION "mr_service_url"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_service_url_wrapper';

-- src/lib.rs:52
-- pgmer2::mr_scores
CREATE  FUNCTION "mr_scores"(
	"ego" TEXT /* &str */
) RETURNS TABLE (
	"node" TEXT,  /* alloc::string::String */
	"ego" TEXT,  /* alloc::string::String */
	"score" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_scores_wrapper';

-- src/lib.rs:140
-- pgmer2::mr_nodes
CREATE  FUNCTION "mr_nodes"() RETURNS TABLE (
	"id" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_nodes_wrapper';

-- src/lib.rs:38
-- pgmer2::mr_node_score
CREATE  FUNCTION "mr_node_score"(
	"ego" TEXT, /* &str */
	"target" TEXT /* &str */
) RETURNS TABLE (
	"node" TEXT,  /* alloc::string::String */
	"ego" TEXT,  /* alloc::string::String */
	"score" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_node_score_wrapper';

-- src/lib.rs:115
-- pgmer2::mr_gravity_nodes
CREATE  FUNCTION "mr_gravity_nodes"(
	"ego" TEXT, /* &str */
	"focus" TEXT /* &str */
) RETURNS TABLE (
	"node" TEXT,  /* alloc::string::String */
	"weight" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_gravity_nodes_wrapper';

-- src/lib.rs:101
-- pgmer2::mr_gravity_graph
CREATE  FUNCTION "mr_gravity_graph"(
	"ego" TEXT, /* &str */
	"focus" TEXT /* &str */
) RETURNS TABLE (
	"node" TEXT,  /* alloc::string::String */
	"ego" TEXT,  /* alloc::string::String */
	"score" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_gravity_graph_wrapper';

-- src/lib.rs:129
-- pgmer2::mr_for_beacons_global
CREATE  FUNCTION "mr_for_beacons_global"() RETURNS TABLE (
	"ego" TEXT,  /* alloc::string::String */
	"dest" TEXT,  /* alloc::string::String */
	"score" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_for_beacons_global_wrapper';

-- src/lib.rs:152
-- pgmer2::mr_edges
CREATE  FUNCTION "mr_edges"() RETURNS TABLE (
	"source" TEXT,  /* alloc::string::String */
	"target" TEXT,  /* alloc::string::String */
	"weight" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_edges_wrapper';

-- src/lib.rs:65
-- pgmer2::mr_edge
CREATE  FUNCTION "mr_edge"(
	"src" TEXT, /* &str */
	"dest" TEXT, /* &str */
	"weight" double precision /* f64 */
) RETURNS TABLE (
	"node" TEXT,  /* alloc::string::String */
	"ego" TEXT,  /* alloc::string::String */
	"score" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_edge_wrapper';

-- src/lib.rs:91
-- pgmer2::mr_delete_node
CREATE  FUNCTION "mr_delete_node"(
	"ego" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<&str, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_delete_node_wrapper';

-- src/lib.rs:80
-- pgmer2::mr_delete_edge
CREATE  FUNCTION "mr_delete_edge"(
	"ego" TEXT, /* &str */
	"target" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<&str, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_delete_edge_wrapper';

-- src/lib.rs:164
-- pgmer2::mr_connected
CREATE  FUNCTION "mr_connected"(
	"ego" TEXT /* &str */
) RETURNS TABLE (
	"src" TEXT,  /* alloc::string::String */
	"dest" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mr_connected_wrapper';
